New refactor for purchase flow
satispay/prestashop-plugin pull request #1
Opened 2021-08-04 08:59 UTC by MichaelBattistonBitbull

2021-08-05 15:45 UTC, springerin requested changes

2021-08-05 15:45 UTC, springerin commented on controllers/front/callback.php
> +        $orderId = Order::getOrderByCartId($payment->metadata->cart_id);
gerOrderByCartId può lanciare eccezioni?

2021-08-06 13:15 UTC, MichaelBattistonBitbull commented on controllers/front/callback.php
> +        $orderId = Order::getOrderByCartId($payment->metadata->cart_id);
No, la funzione getOrderByCartId torna "false" se l'ordine non esiste. 
A seguito di ciò la riga sottostante `$order = new Order($orderId);` crea un ordine vuoto che fa fallire la condizione `if ($order->current_state == (int)(Configuration::get('SATISPAY_PENDING_STATE')))` impedendo quindi la generazione di eccezioni.

2021-08-11 07:49 UTC, springerin approved these changes

2021-11-18 17:05 UTC, merged